# fly.toml app configuration file generated for lias-url-shortener on 2024-09-17T10:18:07+12:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'lias-url-shortener'
primary_region = 'syd'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
